export {default as AboutPage} from "./AboutPage"
export {default as ArticlePage} from "./ArticlePage"
export {default as BlogPage} from "./BlogPage"
export {default as ContactPage} from "./ContactPage"
export {default as CoursePage} from "./CoursePage"
export {default as CoursesPage} from "./CoursesPage"
export {default as Home} from "./Home"
export {default as SolutionsPage} from "./SolutionsPage"