export {default as ContactPage} from "../pages/ContactPage"
export {default as AboutPage} from "../pages/AboutPage"
export {default as Home} from "../pages/Home"
export {default as SolutionsPage} from "../pages/SolutionsPage"
export {default as CoursesPage} from "./CoursesPage"
export {default as CoursePage} from "../pages/CoursePage"
export {default as BlogPage} from "../pages/BlogPage"