export {default as Cards} from './Cards'
export {default as Cards2} from './Cards2'
export {default as History} from './History'
export {default as Mision} from './Mision'
export {default as Vision} from './Vision'
export {default as Values} from './Values'
export {default as OurTeam} from './OurTeam'
export {default as Company} from './Company'